version: '3.8'
services:
  backend:
    build:
      context: ./CodeTestApi
      dockerfile: ./CodeTestApi.Host/Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  # angular:
  #   build:
  #     context: ./CodeTestFrontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./CodeTestFrontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "4200:4200"
  #   command: npm run start

volumes:
  mongo-data:
